### ISSUE TITLE
crash on opening Baca db

### ISSUE THREAD

**Issue by jimalbright** [sillsdev/solid#4] opened 2019-03-01 17:52 UTC
Please e-mail this to solid@projects.palaso.org Msg: Data at the root level is invalid. Line 1, position 1.
Source: System.Xml
Assembly: System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
Stack:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at SolidGui.Engine.SolidSettings.OpenSolidFile(String filePath)
   at SolidGui.MainWindowPM.LoadSettingsFromExistingFile(String solidFilePath)
   at SolidGui.MainWindowPM.OpenDictionary(String dictionaryPath, String templatePath, Boolean forceUnicode)
   at SolidGui.Program.TryToOpen(String fileName, MainWindowPM model, MainWindowView form)
   at SolidGui.Program.Main(String[] args)
Thread: 
Thread UI culture: en-US
Exception: System.Xml.XmlException

--Error Reporting Properties--
Version: Version 0.21.3 (apparent build date: 21-Feb-2018)
CommandLine: "C:\Program Files (x86)\Solid\Solid.exe" "C:\D\dictionaries\ginger\Baca\BacaOut.db"
CurrentDirectory: C:\Windows
MachineName: SWD-ALBRIGHT-LT
OSVersion: Windows 10 
DotNetVersion: 4.0.30319.42000
WorkingSet: 23842816
UserDomainName: WAXHAW
UserName: Albright
Culture: en-US
KeyboardAdaptors: WinKeyboardAdaptor

--Log--
Friday, March 1, 2019
12:29:53 PM	App Launched with ["C:\Program Files (x86)\Solid\Solid.exe" "C:\D\dictionaries\ginger\Baca\BacaOut.db"]
12:29:54 PM	Keyboard adaptors in use: WinKeyboardAdaptor
12:29:54 PM	Loading Solid file from C:\D\dictionaries\ginger\Baca\BacaOut.solid
12:30:04 PM	Loading Solid file from C:\D\dictionaries\ginger\Baca\BacaOut.solid
12:30:05 PM	Exception: Data at the root level is invalid. Line 1, position 1.
Details of most recent events:
12:29:53 PM	App Launched with ["C:\Program Files (x86)\Solid\Solid.exe" "C:\D\dictionaries\ginger\Baca\BacaOut.db"]
12:29:54 PM	Keyboard adaptors in use: WinKeyboardAdaptor
12:29:54 PM	Loading Solid file from C:\D\dictionaries\ginger\Baca\BacaOut.solid
12:30:04 PM	Loading Solid file from C:\D\dictionaries\ginger\Baca\BacaOut.solid
12:30:05 PM	Exception: Data at the root level is invalid. Line 1, position 1.

To Reproduce: 
open BacaOut.db

**Comment by jimalbright** [comment] 2019-03-01 19:36
\id Baca jaa test

\lx à
\ps POSS adj
\cl
\ge 2s poss
\gn 2s  poss

\lx à≠fám
\ps n
\cl 3?
\ge diarrhea
\gn diarrhée

**Comment by jimalbright** [comment] 2019-03-01 19:37
or missing the \id line

**Comment by bbryson** [comment] 2024-06-18 03:20
I tried with this sample data just now (with Solid 1.0.0), both with and without the id line.  I didn't get a crash either time.

This looks sort of like what happens when records don't begin with \lx, or when there are other markers before \lx other than \id.

**Comment by megahirt** [comment] 2024-06-18 03:21
OK, would you agree that this issue can be closed as "cannot reproduce"?

**Comment by megahirt** [comment] 2024-06-18 03:43
I followed @jimalbright 's steps in this issue but could not reproduce the problem on [Solid v1.0](https://github.com/sillsdev/solid/releases/tag/v1.0).  I am closing this as "cannot reproduce".  Feel free to re-open if I've missed something and you can provide steps to reproduce the crash.

**Closed by megahirt** 2024-06-18 03:43 UTC
Labels: bug
